assign8: assign8.o
	gcc -g assign8.o -o assign8 

assign8.o: assign8.c
	gcc -c assign8.c 

assign8-2: assign8-2.o
	gcc -g assign8-2.o -o assign8-2 

assign8-2.o: assign8-2.c
	gcc -c assign8-2.c 

clean:
	rm *.o assign8 assign8-2       
